version: 2

sources:

  - name: raw

    description: "Raw tables loaded into BigQuery."

    database: olist-gcp-data-engineering

    schema: olist_raw

    tables:

      - name: customers
        identifier: olist_customers_dataset

      - name: orders
        identifier: olist_orders_dataset

      - name: products
        identifier: olist_products_dataset

      - name: sellers
        identifier: olist_sellers_dataset

      - name: geolocation
        identifier: olist_geolocation_dataset

      - name: order_items
        identifier: olist_order_items_dataset

      - name: order_payments
        identifier: olist_order_payments_dataset

      - name: order_reviews
        identifier: olist_order_reviews_dataset

      - name: category_translation
        identifier: product_category_name_translation