# olist:
#   target: dev

#   outputs:

#     dev:
#       type: duckdb

#       path: /opt/airflow/warehouse/olist.duckdb

#       threads: 4

olist:
  target: dev

  outputs:

    dev:
      type: duckdb

      path: ../warehouse/olist.duckdb

      threads: 4