olist:
  target: dev

  outputs:

    dev:
      type: bigquery
      method: service-account

      project: olist-gcp-data-engineering

      dataset: olist_analytics

      threads: 4

      # keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '../config/service-account.json') }}"

      location: asia-southeast1

      priority: interactive