version: 2

models:

  - name: dim_customer
    description: "Customer dimension."

    columns:
      - name: customer_id
        description: "Primary key."
        tests:
          - unique
          - not_null

  - name: dim_product
    description: "Product dimension."

    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_seller
    description: "Seller dimension."

    columns:
      - name: seller_id
        tests:
          - unique
          - not_null

  - name: dim_geolocation
    description: "Geolocation dimension."

  - name: dim_date
    description: "Date dimension."

    columns:
      - name: order_date
        tests:
          - unique
          - not_null

  - name: fact_orders
    description: "Order fact table."

    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id

  - name: fact_order_items
    description: "Order item fact table."

  - name: fact_payments
    description: "Payment fact table."

    columns:
      - name: order_id
        tests:
          - not_null

  - name: fact_reviews
    description: "Review fact table."

  - name: executive_dashboard
    description: "Executive KPI summary model."